all:
  hosts:
    master1:
      ansible_host: 172.20.11.182
      ip: 172.20.11.182
      access_ip: 172.20.11.182
    node1:
      ansible_host: 172.20.11.127
      ip: 172.20.11.127
      access_ip: 172.20.11.127
  children:
    kube-master:
      hosts:
        master1:
    kube-node:
      hosts:
        node1:
    etcd:
      hosts:
        master1:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
