all:
  hosts:
    master:
      ansible_host: 172.20.11.223
      ip: 172.20.11.223
      access_ip: 172.20.11.223
    node1:
      ansible_host: 172.20.11.184
      ip: 172.20.11.184
      access_ip: 172.20.11.184
  children:
    kube-master:
      hosts:
        master:
    kube-node:
      hosts:
        node1:
    etcd:
      hosts:
        master:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
